markdown: rdiscount
pygments: true
permalink: pretty
url: szabster.net
title: Mihail Szabolcs
slug: Senior Software Engineer, Open Source Evangelist
author: Mihail Szabolcs
email: http://www.google.com/recaptcha/mailhide/d?k=01frET0_aGQ9WM5QjAxt6YDg==&c=_ElEufb1P2CzS9bv8kXQv16haDk3BzjEFqjFtUIW1P8=
atom: http://feeds.feedburner.com/szabsternet
